Repository BorryJJong/KnockKnock-API, pull requests merged in 2022-06, with the labels that each got.

#29 Build: orm 수정 배포
  dist/config/orm.js
  dist/config/orm.js.map
  dist/tsconfig.build.tsbuildinfo
Labels: Other

#31 Fix: 블로그챌린지 엔티티수정
  src/challenges/challenges.repository.ts
  src/config/orm.ts
  src/entities/BlogChallenge.ts
  src/entities/BlogChallenges.ts
Labels: bugFix

#32 Add: Dist
  dist/challenges/challenges.repository.js
  dist/challenges/challenges.repository.js.map
  dist/config/orm.js
  dist/config/orm.js.map
  dist/entities/BlogChallenge.d.ts
  dist/entities/BlogChallenge.js
  dist/entities/BlogChallenge.js.map
  dist/entities/BlogChallenges.js
  dist/entities/BlogChallenges.js.map
  dist/tsconfig.build.tsbuildinfo
Labels: dist

#33 Refactor: typeorm 마이그레이션을 이용하기 위한 코드 수정
  ormconfig.ts
  output/ormconfig.json
  package.json
  src/config/orm.ts
  src/entities/migrations/1654331813994-InitDatabase.ts
  src/main.ts
Labels: refactor

#38 eslint 적용 자동화
  .eslintrc.js
  .prettierrc
  ecosystem.config.js
  package.json
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/dto/auth.dto.ts
  src/auth/jwt/jwt.guard.ts
  src/auth/jwt/jwt.payload.ts
  src/auth/jwt/jwt.strategy.ts
  src/challenges/challenges.controller.spec.ts
  src/challenges/challenges.controller.ts
  src/challenges/challenges.entity.ts
  src/challenges/challenges.module.ts
  src/challenges/challenges.repository.ts
  src/challenges/challenges.service.spec.ts
  src/challenges/challenges.service.ts
  src/challenges/dto/challenges.dto.ts
  src/config/orm.ts
  src/config/swagger.ts
  src/entities/BlogChallenges.ts
  src/entities/BlogComment.ts
  src/entities/BlogImage.ts
  src/entities/BlogLike.ts
  src/entities/BlogPost.ts
  src/entities/BlogPromotion.ts
  src/entities/Challenges.ts
  src/entities/Promotions.ts
  src/entities/User.ts
  src/feed/dto/feed.dto.ts
  src/feed/feed.controller.spec.ts
  src/feed/feed.controller.ts
  src/feed/feed.module.ts
  src/feed/feed.service.spec.ts
  src/feed/feed.service.ts
  src/image/image.controller.ts
  src/image/image.module.ts
  src/image/image.service.ts
  src/main.ts
  src/promotions/promotions.controller.spec.ts
  src/promotions/promotions.controller.ts
  src/promotions/promotions.module.ts
  src/promotions/promotions.service.spec.ts
  src/promotions/promotions.service.ts
  src/shared/entities/base.entity.ts
  src/shared/response_entities/base.response.ts
  src/shared/response_entities/feed/temp.response.ts
  src/shared/utils/index.ts
  src/users/dto/users.dto.ts
  src/users/users.controller.ts
  src/users/users.entity.ts
  src/users/users.module.ts
  src/users/users.repository.ts
  src/users/users.service.ts
  yarn.lock
Labels: refactor

#41 typescript 의존서 수정 및 미사용 파일 제거
  package-lock.json
  package.json
Labels: refactor

#39 Refactor/erd와 엔티티파일 코드 싱크 맞추기
  ormconfig.ts
  package.json
  src/api/challenges/challenges.controller.spec.ts
  src/api/challenges/challenges.controller.ts
  src/api/challenges/challenges.entity.ts
  src/api/challenges/challenges.module.ts
  src/api/challenges/challenges.repository.ts
  src/api/challenges/challenges.service.spec.ts
  src/api/challenges/challenges.service.ts
  src/api/challenges/dto/challenges.dto.ts
  src/api/feed/dto/feed.dto.ts
  src/api/feed/feed.controller.spec.ts
  src/api/feed/feed.controller.ts
  src/api/feed/feed.module.ts
  src/api/feed/feed.service.spec.ts
  src/api/feed/feed.service.ts
  src/api/image/image.controller.ts
  src/api/image/image.module.ts
  src/api/image/image.service.ts
  src/api/promotions/promotions.controller.spec.ts
  src/api/promotions/promotions.controller.ts
  src/api/promotions/promotions.module.ts
  src/api/promotions/promotions.service.spec.ts
  src/api/promotions/promotions.service.ts
  src/api/users/dto/users.dto.ts
  src/api/users/users.controller.ts
  src/api/users/users.entity.ts
  src/api/users/users.module.ts
  src/api/users/users.repository.ts
  src/api/users/users.service.ts
  src/app.module.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/dto/auth.dto.ts
  src/auth/jwt/jwt.strategy.ts
  src/config/orm.ts
  src/entities/BlogChallenges.ts
  src/entities/BlogComment.ts
  src/entities/BlogImage.ts
  src/entities/BlogLike.ts
  src/entities/BlogPost.ts
  src/entities/BlogPromotion.ts
  src/entities/Challenges.ts
  src/entities/Promotions.ts
  src/entities/User.ts
  src/entities/migrations/1654331813994-InitDatabase.ts
  src/shared/entities/base.entity.ts
Labels: refactor

#45 Feature: 피드 등록 - 매장주소,xy좌표 값 nullable 처리
  src/api/feed/feed.service.ts
  src/entities/BlogPost.ts
Labels: feature, 피드 개발

#48 Feature/피드 목록 조회하기 api 개발
  package.json
  src/api/challenges/challenges.controller.spec.ts
  src/api/challenges/challenges.controller.ts
  src/api/challenges/challenges.entity.ts
  src/api/challenges/challenges.interface.ts
  src/api/challenges/challenges.repository.ts
  src/api/challenges/challenges.service.spec.ts
  src/api/challenges/challenges.service.ts
  src/api/challenges/challenges.spec.ts
  src/api/challenges/dto/challenges.dto.ts
  src/config/orm.ts
  src/entities/Challenges.ts
  src/entities/User.ts
  src/entities/migrations/1656143433844-InitDatabase.ts
  yarn.lock
Labels: feature, 챌린지 개발
