Repository BorryJJong/KnockKnock-API, pull requests merged in 2022-09, with the labels that each got.

#90 feature: scale 추가 및 컬럼명 변경
  src/api/feed/dto/feed.dto.ts
  src/api/feed/feed.service.ts
  src/api/feed/repository/blogPost.repository.ts
  src/entities/BlogPost.ts
Labels: feature, 피드 개발

#68 챌린지 DTO명명 수정 및 상세조회 commit
  .gitignore
  src/api/challenges/challenges.controller.ts
  src/api/challenges/challenges.repository.ts
  src/api/challenges/challenges.service.ts
  src/api/challenges/dto/challenges.dto.ts
  src/entities/Challenges.ts
Labels: feature, 챌린지 개발

#91 배포: 챌린지 상세(일부 로직 수정)
  dist/api/challenges/challenges.controller.d.ts
  dist/api/challenges/challenges.controller.js
  dist/api/challenges/challenges.controller.js.map
  dist/api/challenges/challenges.repository.d.ts
  dist/api/challenges/challenges.repository.js
  dist/api/challenges/challenges.repository.js.map
  dist/api/challenges/challenges.service.d.ts
  dist/api/challenges/challenges.service.js
  dist/api/challenges/challenges.service.js.map
  dist/api/challenges/dto/challenges.dto.d.ts
  dist/api/challenges/dto/challenges.dto.js
  dist/api/challenges/dto/challenges.dto.js.map
  dist/api/feed/dto/feed.dto.d.ts
  dist/api/feed/dto/feed.dto.js
  dist/api/feed/dto/feed.dto.js.map
  dist/api/feed/feed.service.js
  dist/api/feed/feed.service.js.map
  dist/api/feed/repository/blogPost.repository.js
  dist/api/feed/repository/blogPost.repository.js.map
  dist/entities/BlogPost.d.ts
  dist/entities/BlogPost.js
  dist/entities/BlogPost.js.map
  dist/entities/Challenges.js
  dist/entities/Challenges.js.map
  dist/tsconfig.build.tsbuildinfo
  src/api/challenges/challenges.controller.ts
  src/api/challenges/challenges.repository.ts
  src/api/challenges/challenges.service.ts
  src/api/challenges/dto/challenges.dto.ts
Labels: dist
