Repository BorryJJong/KnockKnock-API, pull requests merged in 2022-07, with the labels that each got.

#54 피드 필터링에 의한 목록 조회
  src/api/challenges/dto/challenges.dto.ts
  src/api/feed/blogChallenges.repository.ts
  src/api/feed/blogImage.interface.ts
  src/api/feed/blogImage.repository.ts
  src/api/feed/blogPost.interface.ts
  src/api/feed/blogPost.repository.ts
  src/api/feed/dto/feed.dto.ts
  src/api/feed/feed.controller.ts
  src/api/feed/feed.service.ts
  src/shared/dto/pagenation.dto.ts
  src/shared/enums/enum.ts
Labels: feature, 피드 개발

#56 챌린지 키워드에 "전체" 항목 추가
  src/api/challenges/challenges.service.ts
Labels: feature, 피드 개발

#58 정해진 컨벤션에 맞게 DTO 네이밍 수정
  src/api/challenges/challenges.controller.ts
  src/api/challenges/challenges.service.ts
  src/api/challenges/dto/challenges.dto.ts
  src/api/feed/blogPromotion.repository.ts
  src/api/feed/dto/feed.dto.ts
  src/api/feed/feed.controller.ts
  src/api/feed/feed.module.ts
  src/api/feed/feed.service.ts
  src/api/feed/interface/blogImage.interface.ts
  src/api/feed/interface/blogPost.interface.ts
  src/api/feed/repository/blogChallenges.repository.ts
  src/api/feed/repository/blogImage.repository.ts
  src/api/feed/repository/blogPost.repository.ts
  src/api/feed/repository/blogPromotion.repository.ts
  src/shared/dto/pagenation.dto.ts
Labels: refactor

#64 Add: Dist
  .gitignore
  dist/src/api/challenges/challenges.controller.d.ts
  dist/src/api/challenges/challenges.controller.js
  dist/src/api/challenges/challenges.controller.js.map
  dist/src/api/challenges/challenges.service.d.ts
  dist/src/api/challenges/challenges.service.js
  dist/src/api/challenges/challenges.service.js.map
  dist/src/api/challenges/dto/challenges.dto.d.ts
  dist/src/api/challenges/dto/challenges.dto.js
  dist/src/api/challenges/dto/challenges.dto.js.map
  dist/src/api/feed/dto/feed.dto.d.ts
  dist/src/api/feed/dto/feed.dto.js
  dist/src/api/feed/dto/feed.dto.js.map
  dist/src/api/feed/feed.controller.d.ts
  dist/src/api/feed/feed.controller.js
  dist/src/api/feed/feed.controller.js.map
  dist/src/api/feed/feed.module.js
  dist/src/api/feed/feed.module.js.map
  dist/src/api/feed/feed.service.d.ts
  dist/src/api/feed/feed.service.js
  dist/src/api/feed/feed.service.js.map
  dist/tsconfig.build.tsbuildinfo
Labels: dist

#65 Dist/develop
  ecosystem.config.js
Labels: dist

#62 Feature/피드상세조회
  src/api/feed/dto/feed.dto.ts
  src/api/feed/feed.controller.ts
  src/api/feed/feed.service.ts
  src/api/feed/repository/blogChallenges.repository.ts
  src/api/feed/repository/blogImage.repository.ts
  src/api/feed/repository/blogPost.repository.ts
  src/api/feed/repository/blogPromotion.repository.ts
  src/shared/response_entities/feed/temp.response.ts
Labels: feature, 피드 개발

#70 feature/시간변환처리 완료
  src/shared/utils/index.ts
Labels: feature

#71 Feature/피드 게시글 목록 full 구현
  .gitignore
  dist/src/api/challenges/challenges.controller.d.ts
  dist/src/api/challenges/challenges.controller.js
  dist/src/api/challenges/challenges.controller.js.map
  dist/src/api/challenges/challenges.service.d.ts
  dist/src/api/challenges/challenges.service.js
  dist/src/api/challenges/challenges.service.js.map
  dist/src/api/challenges/dto/challenges.dto.d.ts
  dist/src/api/challenges/dto/challenges.dto.js
  dist/src/api/challenges/dto/challenges.dto.js.map
  dist/src/api/feed/dto/feed.dto.d.ts
  dist/src/api/feed/dto/feed.dto.js
  dist/src/api/feed/dto/feed.dto.js.map
  dist/src/api/feed/feed.controller.d.ts
  dist/src/api/feed/feed.controller.js
  dist/src/api/feed/feed.controller.js.map
  dist/src/api/feed/feed.module.js
  dist/src/api/feed/feed.module.js.map
  dist/src/api/feed/feed.service.d.ts
  dist/src/api/feed/feed.service.js
  dist/src/api/feed/feed.service.js.map
  dist/src/api/feed/interface/blogImage.interface.d.ts
  dist/src/api/feed/interface/blogImage.interface.js
  dist/src/api/feed/interface/blogImage.interface.js.map
  dist/src/api/feed/interface/blogPost.interface.d.ts
  dist/src/api/feed/interface/blogPost.interface.js
  dist/src/api/feed/interface/blogPost.interface.js.map
  dist/src/api/feed/repository/blogChallenges.repository.d.ts
  dist/src/api/feed/repository/blogChallenges.repository.js
  dist/src/api/feed/repository/blogChallenges.repository.js.map
  dist/src/api/feed/repository/blogImage.repository.d.ts
  dist/src/api/feed/repository/blogImage.repository.js
  dist/src/api/feed/repository/blogImage.repository.js.map
  dist/src/api/feed/repository/blogPost.repository.d.ts
  dist/src/api/feed/repository/blogPost.repository.js
  dist/src/api/feed/repository/blogPost.repository.js.map
  dist/src/api/feed/repository/blogPromotion.repository.d.ts
  dist/src/api/feed/repository/blogPromotion.repository.js
  dist/src/api/feed/repository/blogPromotion.repository.js.map
  dist/src/shared/dto/Pagenation.dto.d.ts
  dist/src/shared/dto/Pagenation.dto.js
  dist/src/shared/dto/Pagenation.dto.js.map
  dist/src/shared/enums/enum.d.ts
  dist/src/shared/enums/enum.js
  dist/src/shared/enums/enum.js.map
  dist/tsconfig.build.tsbuildinfo
  src/api/feed/dto/feed.dto.ts
  src/api/feed/feed.controller.spec.ts
  src/api/feed/feed.controller.ts
  src/api/feed/feed.service.ts
  src/api/feed/interface/blogImage.interface.ts
  src/api/feed/interface/blogPost.interface.ts
  src/api/feed/repository/blogPost.repository.ts
  src/api/users/dto/users.dto.ts
  src/api/users/users.repository.ts
Labels: feature, 피드 개발

#74 Dist/develop
  dist/src/api/challenges/challenges.controller.d.ts
  dist/src/api/challenges/challenges.controller.js
  dist/src/api/challenges/challenges.controller.js.map
  dist/src/api/challenges/challenges.service.d.ts
  dist/src/api/challenges/challenges.service.js
  dist/src/api/challenges/challenges.service.js.map
  dist/src/api/challenges/dto/challenges.dto.d.ts
  dist/src/api/challenges/dto/challenges.dto.js
  dist/src/api/challenges/dto/challenges.dto.js.map
  dist/src/api/feed/dto/feed.dto.d.ts
  dist/src/api/feed/dto/feed.dto.js
  dist/src/api/feed/dto/feed.dto.js.map
  dist/src/api/feed/feed.controller.d.ts
  dist/src/api/feed/feed.controller.js
  dist/src/api/feed/feed.controller.js.map
  dist/src/api/feed/feed.module.js
  dist/src/api/feed/feed.module.js.map
  dist/src/api/feed/feed.service.d.ts
  dist/src/api/feed/feed.service.js
  dist/src/api/feed/feed.service.js.map
  dist/src/api/users/dto/users.dto.js.map
  dist/src/api/users/users.repository.d.ts
  dist/src/api/users/users.repository.js
  dist/src/api/users/users.repository.js.map
  dist/src/app.module.js
  dist/src/app.module.js.map
  dist/src/shared/response_entities/feed/temp.response.d.ts
  dist/src/shared/response_entities/feed/temp.response.js
  dist/src/shared/response_entities/feed/temp.response.js.map
  dist/src/shared/utils/index.d.ts
  dist/src/shared/utils/index.js
  dist/src/shared/utils/index.js.map
  dist/tsconfig.build.tsbuildinfo
  src/api/challenges/dto/challenges.dto.ts
Labels: dist

#75 Dist/develop
  .gitignore
  dist/src/api/feed/interface/blogImage.interface.d.ts
  dist/src/api/feed/interface/blogImage.interface.js
  dist/src/api/feed/interface/blogImage.interface.js.map
  dist/src/api/feed/interface/blogPost.interface.d.ts
  dist/src/api/feed/interface/blogPost.interface.js
  dist/src/api/feed/interface/blogPost.interface.js.map
  dist/src/api/feed/repository/blogChallenges.repository.d.ts
  dist/src/api/feed/repository/blogChallenges.repository.js
  dist/src/api/feed/repository/blogChallenges.repository.js.map
  dist/src/api/feed/repository/blogImage.repository.d.ts
  dist/src/api/feed/repository/blogImage.repository.js
  dist/src/api/feed/repository/blogImage.repository.js.map
  dist/src/api/feed/repository/blogPost.repository.d.ts
  dist/src/api/feed/repository/blogPost.repository.js
  dist/src/api/feed/repository/blogPost.repository.js.map
  dist/src/api/feed/repository/blogPromotion.repository.d.ts
  dist/src/api/feed/repository/blogPromotion.repository.js
  dist/src/api/feed/repository/blogPromotion.repository.js.map
  dist/src/api/like/like.controller.d.ts
  dist/src/api/like/like.controller.js
  dist/src/api/like/like.controller.js.map
  dist/src/api/like/like.module.d.ts
  dist/src/api/like/like.module.js
  dist/src/api/like/like.module.js.map
  dist/src/api/like/like.service.d.ts
  dist/src/api/like/like.service.js
  dist/src/api/like/like.service.js.map
  dist/src/api/like/repository/feed.repository.d.ts
  dist/src/api/like/repository/feed.repository.js
  dist/src/api/like/repository/feed.repository.js.map
  dist/src/shared/dto/Pagenation.dto.d.ts
  dist/src/shared/dto/Pagenation.dto.js
  dist/src/shared/dto/Pagenation.dto.js.map
  dist/src/shared/enums/enum.d.ts
  dist/src/shared/enums/enum.js
  dist/src/shared/enums/enum.js.map
Labels: dist
