Repository BorryJJong/KnockKnock-API, pull requests merged in 2022-12, with the labels that each got.

#118 feature: 댓글삭제 개발
  src/api/feed/dto/feed.dto.ts
  src/api/feed/feed.controller.ts
  src/api/feed/feed.service.ts
  src/api/feed/repository/blogComment.repository.ts
  src/entities/BlogComment.ts
  src/shared/response_entities/feed/temp.response.ts
Labels: feature

#122 Feature/api 에러 응답값 구현
  package.json
  src/api/challenges/challenges.repository.ts
  src/api/feed/feed.service.ts
  src/api/like/like.service.ts
  src/api/users/users.validator.ts
  src/app.controller.ts
  src/auth/jwt/jwt.guard.ts
  src/auth/kakao.service.ts
  src/entities/ErrorTemplate.ts
  src/main.ts
  src/shared/enums/enum.ts
  src/shared/filter/HttpException.Filter.ts
  yarn.lock
Labels: feature, API 응답값 구현

#124 feature: 피드 수정 개발
  src/api/feed/dto/feed.dto.ts
  src/api/feed/feed.controller.ts
  src/api/feed/feed.service.ts
  src/api/feed/interface/blogPost.interface.ts
  src/api/feed/repository/blogChallenges.repository.ts
  src/api/feed/repository/blogPost.repository.ts
  src/api/feed/repository/blogPromotion.repository.ts
  src/shared/response_entities/feed/temp.response.ts
Labels: feature, 피드 개발

#125 피드 목록 조회 데이터 수정
  src/api/challenges/challenges.module.ts
  src/api/feed/feed.controller.ts
  src/api/feed/feed.module.ts
  src/api/feed/feed.service.ts
  src/api/feed/interface/blogComment.interface.ts
  src/api/feed/interface/blogPost.interface.ts
  src/api/feed/repository/blogComment.repository.ts
  src/api/feed/repository/blogImage.repository.ts
  src/api/like/like.controller.ts
  src/api/like/like.interface.ts
  src/api/like/like.module.ts
  src/api/like/like.service.ts
  src/api/like/repository/like.repository.ts
  src/api/users/users.controller.ts
  src/api/users/users.interface.ts
  src/api/users/users.repository.ts
  src/auth/jwt/jwt.guard.ts
  src/auth/jwt/jwtAccessToken.strategy.ts
  src/auth/jwt/jwtNoneRequired.guard.ts
  src/entities/BlogComment.ts
  src/shared/utils/index.ts
Labels: 피드 개발

#127 Dist/develop
  package.json
  yarn.lock
Labels: dist

#128 Dist/develop
  dist/main.js
  dist/main.js.map
  dist/tsconfig.build.tsbuildinfo
  src/main.ts
Labels: dist

#129 Dist/develop
  dist/api/users/users.repository.js
  dist/api/users/users.repository.js.map
  dist/tsconfig.build.tsbuildinfo
  src/api/users/users.repository.ts
Labels: dist

#132 애플 로그인 구현
  .env.example
  package.json
  src/api/users/users.controller.ts
  src/api/users/users.module.ts
  src/api/users/users.validator.ts
  src/auth/apple.service.ts
  src/auth/auth.interface.ts
  src/auth/auth.module.ts
  src/auth/kakao.service.ts
  yarn.lock
Labels: feature, 애플 소셜 로그인 구현

#133 애플 로그인 배포
  dist/api/users/users.controller.d.ts
  dist/api/users/users.controller.js
  dist/api/users/users.controller.js.map
  dist/api/users/users.module.js
  dist/api/users/users.module.js.map
  dist/api/users/users.validator.js
  dist/api/users/users.validator.js.map
  dist/auth/apple.service.d.ts
  dist/auth/apple.service.js
  dist/auth/apple.service.js.map
  dist/auth/auth.interface.d.ts
  dist/auth/auth.interface.js
  dist/auth/auth.interface.js.map
  dist/auth/auth.module.js
  dist/auth/auth.module.js.map
  dist/auth/kakao.service.d.ts
  dist/auth/kakao.service.js.map
  dist/tsconfig.build.tsbuildinfo
Labels: 애플 소셜 로그인 구현

#135 피드 조회 관련 API 수정
  src/api/feed/feed.controller.ts
  src/api/feed/feed.service.ts
  src/api/feed/interface/blogPost.interface.ts
  src/api/feed/repository/blogComment.repository.ts
  src/api/feed/repository/blogPost.repository.ts
Labels: feature, 피드 개발

#137 회원 탈퇴시 로직 수정
  src/api/users/users.repository.ts
  src/api/users/users.service.ts
  src/shared/enums/enum.ts
Labels: feature, 피드 개발

#138 피드 삭제 API 구현
  src/api/feed/dto/feed.dto.ts
  src/api/feed/feed.controller.ts
  src/api/feed/feed.module.ts
  src/api/feed/feed.service.ts
  src/api/feed/feed.validator.ts
  src/api/feed/interface/blogPost.interface.ts
  src/api/feed/repository/blogPost.repository.ts
  src/api/users/users.service.ts
  src/entities/BlogPost.ts
Labels: feature, 피드 개발

#139 로그인 완료시 회원 데이터 응답값 제공
  src/api/users/dto/users.dto.ts
  src/api/users/users.controller.ts
  src/auth/dto/auth.dto.ts
  src/auth/kakao.service.ts
  src/entities/User.ts
Labels: feature, 카카오 소셜 로그인 개발, 애플 소셜 로그인 구현

#140 서버 배포
  dist/api/feed/dto/feed.dto.d.ts
  dist/api/feed/dto/feed.dto.js
  dist/api/feed/dto/feed.dto.js.map
  dist/api/feed/feed.controller.d.ts
  dist/api/feed/feed.controller.js
  dist/api/feed/feed.controller.js.map
  dist/api/feed/feed.module.js
  dist/api/feed/feed.module.js.map
  dist/api/feed/feed.service.d.ts
  dist/api/feed/feed.service.js
  dist/api/feed/feed.service.js.map
  dist/api/feed/feed.validator.d.ts
  dist/api/feed/feed.validator.js
  dist/api/feed/feed.validator.js.map
  dist/api/feed/interface/blogPost.interface.d.ts
  dist/api/feed/repository/blogComment.repository.js
  dist/api/feed/repository/blogComment.repository.js.map
  dist/api/feed/repository/blogPost.repository.d.ts
  dist/api/feed/repository/blogPost.repository.js
  dist/api/feed/repository/blogPost.repository.js.map
  dist/api/users/dto/users.dto.d.ts
  dist/api/users/dto/users.dto.js
  dist/api/users/dto/users.dto.js.map
  dist/api/users/users.controller.js
  dist/api/users/users.controller.js.map
  dist/api/users/users.repository.d.ts
  dist/api/users/users.repository.js
  dist/api/users/users.repository.js.map
  dist/api/users/users.service.js
  dist/api/users/users.service.js.map
  dist/auth/dto/auth.dto.d.ts
  dist/auth/dto/auth.dto.js
  dist/auth/dto/auth.dto.js.map
  dist/auth/kakao.service.js
  dist/auth/kakao.service.js.map
  dist/entities/BlogPost.d.ts
  dist/entities/BlogPost.js
  dist/entities/BlogPost.js.map
  dist/entities/User.d.ts
  dist/entities/User.js
  dist/entities/User.js.map
  dist/shared/enums/enum.d.ts
  dist/shared/enums/enum.js
  dist/shared/enums/enum.js.map
  dist/tsconfig.build.tsbuildinfo
Labels: dist

#152 피드 게시글 목록 API에 삭제된 댓글은 포함되지 않게 수정
  src/api/feed/feed.service.ts
  src/api/feed/repository/blogComment.repository.ts
Labels: feature, 피드 개발

#153 피드 상세 API 좋아요 누른 상태 추가
  src/api/feed/dto/feed.dto.ts
  src/api/feed/feed.controller.ts
  src/api/feed/feed.service.ts
  src/api/feed/interface/blogPost.interface.ts
  src/api/feed/repository/blogPost.repository.ts
  src/api/like/like.controller.ts
  src/shared/utils/index.ts
Labels: feature, 피드 개발

#160 회원가입/로그인시 응답값의 스키마 swagger 추가
  src/api/feed/feed.module.ts
  src/api/users/dto/users.dto.ts
  src/api/users/users.controller.ts
Labels: feature

#161 애플에 대한 소셜로그인 분기 처리 추가
  src/api/users/users.controller.ts
  src/api/users/users.service.ts
  src/auth/apple.service.ts
Labels: 애플 소셜 로그인 구현

#162 - 회원만 댓글 등록 가능하게 수정
  src/api/feed/feed.controller.ts
  src/api/feed/feed.service.ts
  src/api/feed/repository/blogComment.repository.ts
Labels: 피드 개발
