Repository BorryJJong/KnockKnock-API, pull requests merged in 2022-11, with the labels that each got.

#98 feature/좋아요 목록 개발
  src/api/feed/dto/feed.dto.ts
  src/api/like/like.controller.ts
  src/api/like/like.service.ts
  src/api/like/repository/feed.repository.ts
  src/shared/response_entities/feed/temp.response.ts
Labels: feature, 좋아요 개발

#100 hotfix: 댓글조회 리턴값 타입 변경
  src/api/feed/dto/feed.dto.ts
Labels: bugFix, 피드 개발

#108 Feature/카카오 소셜 로그인 api
  README.md
  src/api/challenges/challenges.controller.ts
  src/api/challenges/challenges.module.ts
  src/api/challenges/challenges.repository.ts
  src/api/feed/dto/feed.dto.ts
  src/api/like/like.controller.ts
  src/api/like/like.module.ts
  src/api/users/users.controller.ts
  src/api/users/users.interface.ts
  src/api/users/users.repository.ts
  src/api/users/users.service.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/dto/auth.dto.ts
  src/auth/jwt/jwt.guard.ts
  src/auth/jwt/jwt.payload.ts
  src/auth/jwt/jwtAccessToken.strategy.ts
  src/auth/jwt/jwtRefreshToken.strategy.ts
  src/config/swagger.ts
  src/entities/User.ts
  src/shared/response_entities/feed/temp.response.ts
Labels: 카카오 소셜 로그인 개발

#110 회원탈퇴 기능 추가 및 리프래쉬 토큰 기능 수정
  src/api/like/like.module.ts
  src/api/users/users.controller.ts
  src/api/users/users.interface.ts
  src/api/users/users.module.ts
  src/api/users/users.repository.ts
  src/api/users/users.service.ts
  src/auth/kakao.service.ts
  src/entities/User.ts
Labels: 카카오 소셜 로그인 개발

#113 피드 좋아요 버그수정 & 챌린지 조회 권한 제거
  ecosystem.config.js
  src/api/challenges/challenges.controller.ts
  src/api/like/like.controller.ts
Labels: bugFix

#114 좋아요 버그 수정, 챌린지 권한제거
  dist/api/challenges/challenges.controller.js
  dist/api/challenges/challenges.controller.js.map
  dist/api/like/like.controller.js
  dist/tsconfig.build.tsbuildinfo
Labels: dist
